In [ ]:
##which product was ordered most times
#which product was cancelled more
#which customer ordered more, cancelled more
#which seller received more orders

In [1]:
import pandas as pd

In [2]:
products=pd.read_csv('/Users/shamitharamya/Documents/ecommerce-sales-analysis/data/raw_data/olist_products_dataset.csv')

In [74]:
products['product_id'].value_counts()

product_id
1e9e8ef04dbcff4541ed26657ea517e5    1
d05cc9afc85771f597cf4bc9d8f12546    1
71b7afd92c42feab780d5ea512fc7348    1
5c5f3e091101bea69642eb3dd145b17d    1
16d47089f9bc7f16de16cc4bd3b9dd49    1
                                   ..
c154987c6780d1a2b579aae00e53485f    1
1a6c9da4039deae58c2b769f049ae121    1
4cb35e544a1de008f37e069f172f964e    1
b34b2c889f5b26963569cf421254e121    1
106392145fca363410d287a815be6de4    1
Name: count, Length: 32951, dtype: int64

In [75]:
products.shape

(32951, 9)

In [76]:
products['product_category_name'].value_counts()

product_category_name
cama_mesa_banho                  3029
esporte_lazer                    2867
moveis_decoracao                 2657
beleza_saude                     2444
utilidades_domesticas            2335
                                 ...
fashion_roupa_infanto_juvenil       5
casa_conforto_2                     5
pc_gamer                            3
seguros_e_servicos                  2
cds_dvds_musicais                   1
Name: count, Length: 73, dtype: int64

In [37]:
products.shape

(32951, 9)

In [4]:
order_items=pd.read_csv(
    '/Users/shamitharamya/Documents/ecommerce-sales-analysis/data/raw_data/olist_order_items_dataset.csv',
    dtype={'price': 'float', 'freight_value': 'float'},
    parse_dates=['shipping_limit_date']
)

In [5]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [9]:
order_items.duplicated().sum()

np.int64(0)

In [33]:
order_items.shape

(112650, 7)

## which product was ordered more

In [42]:
#no of orders product wise
order_items['product_id'].value_counts()

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
                                   ...
dbc42f8ad8afd0147a5a46be630781f8      1
5d86ed92606c80a89e547cdba3946812      1
0b8750fa58fefe42cf03a9e2e4b8fce6      1
a4758e74e2cdb74d0c4db83594ca14a3      1
350688d9dc1e75ff97be326363655e01      1
Name: count, Length: 32951, dtype: int64

In [44]:
#which product was ordered most no of times
order_items['product_id'].value_counts().head(1)

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
Name: count, dtype: int64

## which product category was ordered more

In [ ]:
product_cat=pd.merge(products[['product_id','product_category_name']], order_items[['order_id','product_id']],on='product_id')

In [32]:
product_cat.head()

,product_id,product_category_name,order_id
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,e17e4f88e31525f7deef66779844ddce
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,5236307716393b7114b53ee991f36956
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,01f66e58769f84129811d43eefd187fb
3,cef67bcfe19066a932b7673e239eb23d,bebes,143d00a4f2dde4e0364ee1821577adb3
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,86cafb8794cb99a9b1b77fc8e48fbbbb

In [34]:
product_cat.shape

(112650, 3)

In [45]:
product_cat['product_category_name'].value_counts()

product_category_name
cama_mesa_banho                  11115
beleza_saude                      9670
esporte_lazer                     8641
moveis_decoracao                  8334
informatica_acessorios            7827
                                 ...
la_cuisine                          14
cds_dvds_musicais                   14
pc_gamer                             9
fashion_roupa_infanto_juvenil        8
seguros_e_servicos                   2
Name: count, Length: 73, dtype: int64

In [ ]:
product_cat['product_category_name'].value_counts().head(1)

product_category_name
cama_mesa_banho    11115
Name: count, dtype: int64

## which product was cancelled more

In [48]:
orders=pd.read_csv('/Users/shamitharamya/Documents/ecommerce-sales-analysis/data/raw_data/olist_orders_dataset.csv',
                   parse_dates=['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date'])

In [49]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [52]:
product_cat=pd.merge(product_cat,orders[['order_id','order_status']],on='order_id')

In [55]:
product_cat.head()

,product_id,product_category_name,order_id,order_status
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,e17e4f88e31525f7deef66779844ddce,delivered
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,5236307716393b7114b53ee991f36956,delivered
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,01f66e58769f84129811d43eefd187fb,delivered
3,cef67bcfe19066a932b7673e239eb23d,bebes,143d00a4f2dde4e0364ee1821577adb3,delivered
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,86cafb8794cb99a9b1b77fc8e48fbbbb,delivered

In [54]:
product_cat['order_status'].value_counts()

order_status
delivered      110197
shipped          1185
canceled          542
invoiced          359
processing        357
unavailable         7
approved            3
Name: count, dtype: int64

In [ ]:
#cancelled products
product_cat[product_cat['order_status']=='canceled']['product_id'].value_counts()

product_id
8397dc503d1a0c2ac7422701884de5a6    6
5c3eaf54e8ee5d5378765ff16df7640b    6
66b1f09e746c05761bcaccf6339bde8d    5
3ea32f63a6aaf8d467e543dedf434ee7    5
c3a52053718435a35e070b991ff546ec    5
                                   ..
afb52012e0c69e1b6af6c48d2a62f760    1
e71589252b1fc69c5a7931ee5028ecf6    1
79ea753b9ec382b3bf6b03d449ac9b3b    1
2eb72d11643aaae8f92fafc9296674c8    1
a0b7d5a992ccda646f2d34e418fff5a0    1
Name: count, Length: 436, dtype: int64

In [ ]:
product_cat[product_cat['order_status']=='canceled']['product_id'].value_counts().head(2)

product_id
8397dc503d1a0c2ac7422701884de5a6    6
5c3eaf54e8ee5d5378765ff16df7640b    6
Name: count, dtype: int64

In [78]:
product_cat[product_cat['order_status']=='canceled']['product_category_name'].value_counts()

product_category_name
esporte_lazer                                     51
utilidades_domesticas                             49
informatica_acessorios                            46
beleza_saude                                      36
moveis_decoracao                                  36
brinquedos                                        34
automotivo                                        30
relogios_presentes                                21
bebes                                             20
ferramentas_jardim                                19
cama_mesa_banho                                   18
telefonia                                         18
cool_stuff                                        16
perfumaria                                        15
papelaria                                         12
instrumentos_musicais                             11
eletronicos                                       11
consoles_games                                    10
eletroportateis                                    8
livros_interesse_geral                             7
fashion_bolsas_e_acessorios                        6
pet_shop                                           5
construcao_ferramentas_seguranca                   5
malas_acessorios                                   4
construcao_ferramentas_jardim                      4
telefonia_fixa                                     3
eletrodomesticos_2                                 3
construcao_ferramentas_iluminacao                  2
climatizacao                                       2
moveis_sala                                        2
dvds_blu_ray                                       2
alimentos_bebidas                                  2
fashion_calcados                                   2
eletrodomesticos                                   2
construcao_ferramentas_construcao                  2
moveis_cozinha_area_de_servico_jantar_e_jardim     2
pc_gamer                                           1
portateis_cozinha_e_preparadores_de_alimentos      1
casa_construcao                                    1
bebidas                                            1
market_place                                       1
artigos_de_natal                                   1
fraldas_higiene                                    1
fashion_roupa_masculina                            1
alimentos                                          1
moveis_escritorio                                  1
audio                                              1
artes                                              1
Name: count, dtype: int64

## which customer ordered more, cancelled more

In [65]:
customers=pd.read_csv('/Users/shamitharamya/Documents/ecommerce-sales-analysis/data/raw_data/olist_customers_dataset.csv')

In [66]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [67]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [ ]:
customer_orders=pd.merge(orders[['order_id','order_status','customer_id']],customers[['customer_id','customer_unique_id']],on='customer_id')

In [69]:
customer_orders.head()

,order_id,order_status,customer_id,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,9ef432eb6251297304e76186b10a928d,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,b0830fb4747a6c6d20dea0b8c802d7ef,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,41ce2a54c0b03bf3443c3d931a367089,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,f88197465ea7920adcdbec7375364d82,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,8ab97904e6daea8866dbdbc4fb7aad2c,72632f0f9dd73dfee390c9b22eb56dd6

In [70]:
customer_orders[customer_orders['order_status']!='canceled']['customer_unique_id'].value_counts()

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
3e43e6105506432c953e165fb2acf44c     9
1b6c7548a2a1f9037c1fd3ddfed95f33     7
ca77025e7201e3b30c44b472ff346268     7
6469f99c1f9dfae7733b25662e7f1782     7
                                    ..
b4d20e099c1aadc325ac4b8bdb309cd6     1
3ed4235d521c24fec4f77d4254e070b8     1
11a70f262b8ebca18b88fcb5a5f6882b     1
20ea80f41970eeef262ab9d652ed5255     1
60350aa974b26ff12caad89e55993bd6     1
Name: count, Length: 95560, dtype: int64

In [71]:
#max ordered recevied from
customer_orders[customer_orders['order_status']!='canceled']['customer_unique_id'].value_counts().head(1)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
Name: count, dtype: int64

In [72]:
customer_orders[customer_orders['order_status']=='canceled']['customer_unique_id'].value_counts()

customer_unique_id
ef0103e9602d12594d19c2b666219bc1    3
391d6062da3dd65b4de4524f28c478de    2
af5454198a97379394cacf676e1e96cb    2
ba84da8c159659f116329563a0a981dd    2
46450c74a0d8c5ca9395da1daac6c120    2
                                   ..
756056dc496b52935b053a6f0d02c68f    1
b14ef688a7c1a52e7437298085d9d62b    1
fe19cddc4dc6f64d8d1733e854bbd9cb    1
d971d35a1a557c99d244f04f838f1c54    1
e90598185d2427a35e32ef241a5c04aa    1
Name: count, Length: 616, dtype: int64

In [73]:
#max orders canceled by 
customer_orders[customer_orders['order_status']=='canceled']['customer_unique_id'].value_counts().head(1)

customer_unique_id
ef0103e9602d12594d19c2b666219bc1    3
Name: count, dtype: int64